(function (_4TellBoost, $, undefined) {
    _4TellBoost.CONFIG = {
        SiteInfo: {
            baseURL: "lkjlkj",
            alias: "",
            GA_UA: "",
            GATrackID: "4TellRecs",
            addCartMethod: "",
            addCartImage: "",
            spacerImage: "",
            emptyImage: "_4TellBoost.loadpath + images/nophoto.gif",
            addCartClass: "addCartClass",
            priceClass: "",
            strikePriceClass: "strikePrice",
            salePriceClass: "",
            pricePrefix: "",
            salePricePrefix: "prefix",
            hideIfNoImage: true,
            minPrice: "$.01",
            custom: true,
            includeBase: true,
            delay: false,
            ABTesting: 0,
            persistentTesting: true,
            timeOut: 4000,
            addCartBtnAtts: "",
            platform: "4Tell3d.js",
            siteEnable: true,
            loadDelayObject: "",
            loadDelayTime: 0,
            blobId: 0,
            noConflict: false
        },
